<?php
/**
 * Addthis share toolkit
 *
 * @package SP_MDL_Social_Share
 */

if (!function_exists('addthis_get_share_vendors')) :
    /**
     * AddThis: List of all the AddThis services currently in use. [05/19/2019]
     * @link https://www.addthis.com/services
     */
    function addthis_get_share_vendors($vendors = 'all', $return = 'array')
    {
        $addthis_share_vendors = array(
            '100zakladok' => array(
                'url' => 'http://www.100zakladok.ru',
                'name' => '100zakladok',
                'category' => 'Bookmarking Site',
                'desc' => __("Using the service 100zakladok.ru you can remember all the links to interesting web pages that are found in the network.", 'addthis-share'),
            ),
            'addressbar' => array(
                'url' => '',
                'name' => 'Address Bar',
                'category' => 'Other',
                'desc' => __("This service represents how often users share your site by copying the page URL from their address bar and sending it via email, IM or other channels.", 'addthis-share'),
            ),
            'adfty' => array(
                'url' => 'http://www.adfty.com',
                'name' => 'Adfty',
                'category' => 'Social News',
                'desc' => __("Adfty is a social bookmarking site where users can submit links and others can vote on them.", 'addthis-share'),
            ),
            'adifni' => array(
                'url' => 'http://www.adifni.com',
                'name' => 'Adifni',
                'category' => 'Bookmarking Site',
                'desc' => __("Arabic Bookmarking site", 'addthis-share'),
            ),
            'advqr' => array(
                'url' => 'http://qr-adv.com',
                'name' => 'ADV QR',
                'category' => 'Tools',
                'desc' => __("Easy to use QR code generator.", 'addthis-share'),
            ),
            'amazonwishlist' => array(
                'url' => 'http://www.amazon.com/gp/registry/wishlist',
                'name' => 'Amazon',
                'category' => 'Shopping Site',
                'desc' => __("Add any item to your public Amazon.com Wish List. You can show everyone what you'd like for your birthday or special occasion.", 'addthis-share'),
            ),
            'amazonsmile' => array(
                'url' => 'https://smile.amazon.com',
                'name' => 'Amazon Smile',
                'category' => 'Other',
                'desc' => __("AmazonSmile is a simple and automatic way for you to support your favorite charitable organization every time you shop, at no cost to you.", 'addthis-share'),
            ),
            'amenme' => array(
                'url' => 'http://www.amenme.com/AmenMe',
                'name' => 'Amen Me!',
                'category' => 'Social Network',
                'desc' => __("Find and vote for your favorite sites for Christians. Get an Amen! for your site.", 'addthis-share'),
            ),
            'aim' => array(
                'url' => 'http://lifestream.aol.com/',
                'name' => 'AOL Lifestream',
                'category' => 'Blogging Platform',
                'desc' => __("AIM Share allows you to share content from sites to your AIM Buddies. The content will appear in your Buddies' lifestream tab on their AIM Buddy List and on their lifestream: http://lifestream.aim.com. Share a site, article or video with your buddies. ", 'addthis-share'),
            ),
            'aolmail' => array(
                'url' => 'http://webmail.aol.com',
                'name' => 'AOL Mail',
                'category' => 'Email/IM Service',
                'desc' => __("Email by AOL, with address book.", 'addthis-share'),
            ),
            'apsense' => array(
                'url' => 'http://www.apsense.com',
                'name' => 'APSense',
                'category' => 'Social Network',
                'desc' => __("APSense is a web 2.0 enabled social network designed to help business owners, online marketers and affiliates build their own personal business network of contacts locally or on a global scale.", 'addthis-share'),
            ),
            'atavi' => array(
                'url' => 'https://atavi.com/',
                'name' => 'Atavi',
                'category' => 'Bookmarking Site',
                'desc' => __("Atavi is a free, yet extremely convenient, web service. Bookmark the websites you need, group them the way you want and sync the bookmarks with any device or browser.", 'addthis-share'),
            ),
            'baidu' => array(
                'url' => 'http://share.baidu.com',
                'name' => 'Baidu',
                'category' => 'Social Network',
                'desc' => __("Baidu is a Chinese search engine for websites, audio files, and images", 'addthis-share'),
            ),
            'balatarin' => array(
                'url' => 'https://www.balatarin.com/',
                'name' => 'Balatarin',
                'category' => 'Social Network',
                'desc' => __("Balatarin is a Persian language social and political link-sharing website aimed primarily at Iranian audiences.", 'addthis-share'),
            ),
            'beat100' => array(
                'url' => 'http://www.beat100.com/',
                'name' => 'Beat100',
                'category' => 'Social Network',
                'desc' => __("Beat100 music video and social network allows users to upload music videos, MP3 music files, photos, advertise gigs and events whilst connecting with friends and other members using our social network and live chat room.", 'addthis-share'),
            ),
            'bitly' => array(
                'url' => 'http://bit.ly/',
                'name' => 'Bit.ly',
                'category' => 'Tools',
                'desc' => __("bit.ly allows users to shorten, share, and track links (URLs). Reducing the URL length makes sharing easier.", 'addthis-share'),
            ),
            'bizsugar' => array(
                'url' => 'http://www.bizsugar.com/',
                'name' => 'BizSugar',
                'category' => 'Social News',
                'desc' => __("bizSugar is a small business community and  social media site where small businesses, entrepreneurs and startups can discover, share and vote for business tips and news on the web.", 'addthis-share'),
            ),
            'bland' => array(
                'url' => 'https://bland.is',
                'name' => 'Bland takkinn',
                'category' => 'Social Network',
                'desc' => __("Bland.is is the largest online marketplace in Iceland. Think of it as an Icelandic Craigslist.", 'addthis-share'),
            ),
            'blogger' => array(
                'url' => 'http://blogger.com',
                'name' => 'Blogger',
                'category' => 'Blogging Platform',
                'desc' => __("Blogger is a free blog publishing tool from Google for easily sharing your thoughts with the world.", 'addthis-share'),
            ),
            'blogkeen' => array(
                'url' => 'http://www.blogkeen.com',
                'name' => 'Blogkeen',
                'category' => 'Tools',
                'desc' => __("Blogkeen is a smart service that keeps you updated on all the blogs and RSS-feeds you follow", 'addthis-share'),
            ),
            'blogmarks' => array(
                'url' => 'http://blogmarks.net/',
                'name' => 'Blogmarks',
                'category' => 'Bookmarking Site',
                'desc' => __("A social bookmarks manager that allows categorization via custom tags. Offers several tools to share content, including synchronization with a weblog.", 'addthis-share'),
            ),
            'bobrdobr' => array(
                'url' => 'http://bobrdobr.ru/',
                'name' => 'Bobrdobr',
                'category' => 'Bookmarking Site',
                'desc' => __("Keep tabs on the Internet, Use tags to systematize, Share links with friends, Create groups on favorite topics.", 'addthis-share'),
            ),
            'bonzobox' => array(
                'url' => 'http://bonzobox.com',
                'name' => 'BonzoBox',
                'category' => 'Bookmarking Site',
                'desc' => __("BonzoBox allows you to save your bookmarks visually and build your own customized home page with live thumbnails of your favourite websites.", 'addthis-share'),
            ),
            'bookmarkycz' => array(
                'url' => 'http://www.bookmarky.cz/',
                'name' => 'Bookmarky.cz',
                'category' => 'Bookmarking Site',
                'desc' => __("Online drag &amp; drop organizer for categorization and sharing of personal links. ", 'addthis-share'),
            ),
            'bookmerkende' => array(
                'url' => 'http://www.bookmerken.de/',
                'name' => 'Bookmerken',
                'category' => 'Bookmarking Site',
                'desc' => __("Remember now, read later. With Bookmerken you can quickly and easily highlight interesting links for reading later.", 'addthis-share'),
            ),
            'box' => array(
                'url' => 'http://www.box.net',
                'name' => 'Box',
                'category' => 'Tools',
                'desc' => __("Box.net is a trusted web-based service for accessing and sharing content from anywhere. Nearly 3 million individuals, small businesses, and Fortune 1000 companies around the world use Box to easily connect with the content and people that matter most.", 'addthis-share'),
            ),
            'buffer' => array(
                'url' => 'https://buffer.com',
                'name' => 'Buffer',
                'category' => 'Tools',
                'desc' => __("Buffer is a simpler and easier way to schedule posts, track the performance of your content, and manage all your accounts in one place.", 'addthis-share'),
            ),
            'camyoo' => array(
                'url' => 'http://www.camyoo.com',
                'name' => 'Camyoo',
                'category' => 'Social Network',
                'desc' => __("Camyoo is a photo and video sharing site devoted to all the picture and video takers, lovers and critics!", 'addthis-share'),
            ),
            'care2' => array(
                'url' => 'http://www.care2.com',
                'name' => 'Care2',
                'category' => 'Social Network',
                'desc' => __("Make it easy for everyone to live a healthy, green lifestyle and impact the causes they care about most.", 'addthis-share'),
            ),
            'cashme' => array(
                'url' => 'https://cash.me/',
                'name' => 'Cash.me',
                'category' => 'Other',
                'desc' => __("Exchange money quickly, easily, and for free.", 'addthis-share'),
            ),
            'citeulike' => array(
                'url' => 'http://www.citeulike.org',
                'name' => 'CiteULike',
                'category' => 'Bookmarking Site',
                'desc' => __("CiteULike is a free service to help you to store, organise and share the scholarly papers you are reading.", 'addthis-share'),
            ),
            'technerd' => array(
                'url' => 'http://www.technerd.com',
                'name' => 'Communicate',
                'category' => 'Social Network',
                'desc' => __("This site was created for all people with technical knowledge, skills, or just technically curious. A great way to share new technology and ideas.", 'addthis-share'),
            ),
            'link' => array(
                'url' => '',
                'name' => 'Copy Link',
                'category' => 'Other',
                'desc' => __("Allow users to easily copy a link to share with others.", 'addthis-share'),
            ),
            'cosmiq' => array(
                'url' => 'http://www.cosmiq.de/lili/srch/',
                'name' => 'COSMiQ',
                'category' => 'Bookmarking Site',
                'desc' => __("One of the biggest Q&amp;A communities in Germany. Users can submit questions and experts will then research &amp; deliver your answer. COSMiQ also provides a Social Bookmarking-Service &quot;COSMiQ Links&quot;, that contains more than 115000 bookmarks.", 'addthis-share'),
            ),
            'cssbased' => array(
                'url' => 'http://cssbased.com',
                'name' => 'CSS Based',
                'category' => 'Other',
                'desc' => __("CSS Based is a project providing web designers a database of well designed css based websites from all around the world.", 'addthis-share'),
            ),
            'diary_ru' => array(
                'url' => 'http://www.diary.ru/',
                'name' => 'Diary.ru',
                'category' => 'Bookmarking Site',
                'desc' => __("Diary.Ru is one of the most popular online diary services in Russia. Users share their own diaries, read other people's diaries, communicate in groups and make friends.", 'addthis-share'),
            ),
            'digg' => array(
                'url' => 'http://digg.com/',
                'name' => 'Digg',
                'category' => 'Social News',
                'desc' => __("Digg is a place for people to discover and share content from anywhere on the web. From the biggest online destinations to the most obscure blog, Digg surfaces the best stuff as voted on by our users.", 'addthis-share'),
            ),
            'diggita' => array(
                'url' => 'http://www.diggita.it/',
                'name' => 'Diggita',
                'category' => 'Social News',
                'desc' => __("Diggita is the Italian version of the American site Digg.", 'addthis-share'),
            ),
            'diigo' => array(
                'url' => 'http://www.diigo.com/',
                'name' => 'Diigo',
                'category' => 'Social Network',
                'desc' => __("Diigo is a powerful research tool and a knowledge-sharing community. ", 'addthis-share'),
            ),
            'douban' => array(
                'url' => 'http://www.douban.com/',
                'name' => 'Douban',
                'category' => 'Social Network',
                'desc' => __("Douban is the main review based social network site in China. It is a Chinese online community for users to share opinions and create content related to movies, books, and music.", 'addthis-share'),
            ),
            'draugiem' => array(
                'url' => 'http://www.draugiem.lv',
                'name' => 'Draugiem.lv',
                'category' => 'Social Network',
                'desc' => __("Draugiem is the largest social networking website in Latvia with approximately 2.6 million registered users.", 'addthis-share'),
            ),
            'edcast' => array(
                'url' => 'http://www.edcast.com/',
                'name' => 'EdCast',
                'category' => 'Social Network',
                'desc' => __("EdCast is a knowledge network built to inspire, empower and educate individuals and organizations to get smarter with daily curated &amp; contextual bite-size insights (SmartBitesTM) with live access to influencers and Subject Matter Experts.", 'addthis-share'),
            ),
            'email' => array(
                'url' => '',
                'name' => 'Email',
                'category' => 'Email/IM Service',
                'desc' => __("AddThis menu email service with address book integration (Gmail, Yahoo Mail, AOL mail, and more).", 'addthis-share'),
            ),
            'mailto' => array(
                'url' => '',
                'name' => 'Email App',
                'category' => 'Email/IM Service',
                'desc' => __("AddThis menu mail program service", 'addthis-share'),
            ),
            'evernote' => array(
                'url' => 'http://www.evernote.com',
                'name' => 'Evernote',
                'category' => 'Other',
                'desc' => __("Evernote allows you to easily capture information in any environment using whatever device or platform you find most convenient, and makes this information accessible and searchable at any time, from anywhere. Did we mention that it's free?", 'addthis-share'),
            ),
            'exchangle' => array(
                'url' => 'http://www.exchangle.com/',
                'name' => 'Exchangle',
                'category' => 'Other',
                'desc' => __("Exchangle is a customized search engine where people from all around the world can share links for personal or business purposes.", 'addthis-share'),
            ),
            'stylishhome' => array(
                'url' => 'http://www.stylishhome.com',
                'name' => 'FabDesign',
                'category' => 'Shopping Site',
                'desc' => __("A bookmarking service and community to find the best design insights, furniture, decor, kitchen, bath, lighting and art. All the stores and sales in one place.", 'addthis-share'),
            ),
            'fabulously40' => array(
                'url' => 'http://fabulously40.com/',
                'name' => 'Fabulously40',
                'category' => 'Social Network',
                'desc' => __("Social network for women of &quot;age.&quot;", 'addthis-share'),
            ),
            'facebook' => array(
                'url' => 'http://www.facebook.com',
                'name' => 'Facebook',
                'category' => 'Social Network',
                'desc' => __("Facebook is a social utility that connects people with friends and others who work, study and live around them. People use Facebook to keep up with friends, upload an unlimited number of photos, post links and videos, and learn more about the people they meet.", 'addthis-share'),
            ),
            'facenama' => array(
                'url' => 'http://facenama.com/',
                'name' => 'Facenama',
                'category' => 'Social Network',
                'desc' => __("Facenama is the largest social network in Iran.", 'addthis-share'),
            ),
            'informazione' => array(
                'url' => 'http://fai.informazione.it',
                'name' => 'Fai Informazione',
                'category' => 'Social News',
                'desc' => __("Fai Informazione is an Italian social publishing service, where users can share their own information and vote articles proposed by other fellow users. Articles are ranked based on their content and their votes for quick retrieval of relevant information.", 'addthis-share'),
            ),
            'thefancy' => array(
                'url' => 'http://www.thefancy.com',
                'name' => 'Fancy',
                'category' => 'Other',
                'desc' => __("Fancy is part store, blog, magazine and wishlist. It's a place to discover great stuff, to curate a collection of things you love, to get updates on your favorite brands and stores and to share your discoveries.", 'addthis-share'),
            ),
            'fashiolista' => array(
                'url' => 'http://www.fashiolista.com',
                'name' => 'Fashiolista',
                'category' => 'Shopping Site',
                'desc' => __("Fashiolista introduces a new way to shop for fashion online. Think twitter, reinvented and redesigned by fashion victims. With Fashiolista you can share your unique style! Discover new fashion trends, brands and stores!", 'addthis-share'),
            ),
            'favable' => array(
                'url' => 'http://www.favable.com',
                'name' => 'FAVable',
                'category' => 'Bookmarking Site',
                'desc' => __("Favables is a simple, easy to use service that allows users to visualize, manage and share their favorite web sites.", 'addthis-share'),
            ),
            'favorites' => array(
                'url' => '',
                'name' => 'Favorites',
                'category' => 'Bookmarking Site',
                'desc' => __("AddThis menu favorites service.", 'addthis-share'),
            ),
            'favoritus' => array(
                'url' => 'http://www.favoritus.com',
                'name' => 'Favoritus',
                'category' => 'Bookmarking Site',
                'desc' => __("Save, manage and backup your favorite links online.", 'addthis-share'),
            ),
            'financialjuice' => array(
                'url' => 'http://www.financialjuice.com',
                'name' => 'Financial Juice',
                'category' => 'Social Network',
                'desc' => __("FinancialJuice is a live financial news and content aggregation social network. We provide Real-Time market updates from all the major news sources, bloggers, twitter personalities and YouTube.", 'addthis-share'),
            ),
            'flipboard' => array(
                'url' => 'https://flipboard.com',
                'name' => 'Flipboard',
                'category' => 'Social News',
                'desc' => __("Flipboard is Your Personal Magazine. It's a single place to discover, collect and share the news you care about. Add your favorite social networks, publications and blogs to stay connected to the topics and people closest to you.", 'addthis-share'),
            ),
            'folkd' => array(
                'url' => 'http://www.folkd.com',
                'name' => 'Folkd',
                'category' => 'Bookmarking Site',
                'desc' => __("Social bookmarking destination. Save your bookmarks online and share them with your friends.", 'addthis-share'),
            ),
            'thefreedictionary' => array(
                'url' => 'http://www.thefreedictionary.com',
                'name' => 'FreeDictionary',
                'category' => 'Bookmarking Site',
                'desc' => __("Online Dictionary - Multiple dictionaries including: English dictionary, medical dictionary, legal dictionary, financial dictionary, computer dictionary, thesaurus, dictionary of acronyms and abbreviations, dictionary of idioms, thesaurus, Columbia encyclopedia, Wikipedia encyclopedia, Hutchinson encyclopedia, examples from classic literature, pronunciations, word browser, glossary. Free access", 'addthis-share'),
            ),
            'gg' => array(
                'url' => 'http://www.gg.pl/',
                'name' => 'GG',
                'category' => 'Social Network',
                'desc' => __("GG is the largest Polish Instant Messenger service.", 'addthis-share'),
            ),
            'gmail' => array(
                'url' => 'http://mail.google.com',
                'name' => 'Gmail',
                'category' => 'Email/IM Service',
                'desc' => __("Email by Google, with address book. Gmail is a web-based email service built on the idea that email can be more intuitive, efficient, and useful.", 'addthis-share'),
            ),
            'govn' => array(
                'url' => 'http://www.go.vn',
                'name' => 'Go.vn',
                'category' => 'Social Network',
                'desc' => __("Go.vn is the biggest social network in Vietnam serving purposes of education, entertainment and communication.", 'addthis-share'),
            ),
            'google' => array(
                'url' => 'http://www.google.com/bookmarks',
                'name' => 'Google Bookmark',
                'category' => 'Bookmarking Site',
                'desc' => __("Access your Google bookmarks from any computer Google Bookmarks lets you save shortcuts to your favorite webpages and navigate to them in seconds. Unlike browser bookmarks that are stored on a single computer, Google bookmarks are stored in your Google Account. This means you can access them from any computer with an Internet connection from the Google Toolbar, the Google Bookmarks iGoogle gadget, or the Google Bookmarks homepage.", 'addthis-share'),
            ),
            'google_classroom' => array(
                'url' => 'https://classroom.google.com/',
                'name' => 'Google Classroom',
                'category' => 'Other',
                'desc' => __("Classroom is a new tool in Google Apps for Education that helps teachers create and organize assignments quickly, provide feedback efficiently, and easily communicate with their classes.", 'addthis-share'),
            ),
            'googletranslate' => array(
                'url' => 'http://translate.google.com',
                'name' => 'Google Translate',
                'category' => 'Tools',
                'desc' => __("Google's free online language translation service instantly translates text and web pages. Supports over 40 languages.", 'addthis-share'),
            ),
            'hackernews' => array(
                'url' => 'http://news.ycombinator.com',
                'name' => 'Hacker News',
                'category' => 'Social News',
                'desc' => __("Hacker News is a social news website focusing on computer science and entrepreneurship. It is run by Paul Graham's investment fund and startup incubator, Y Combinator. In general, content that can be submitted is defined as &quot;anything that gratifies one's intellectual curiosity&quot;.", 'addthis-share'),
            ),
            'hatena' => array(
                'url' => 'http://b.hatena.ne.jp/',
                'name' => 'Hatena',
                'category' => 'Bookmarking Site',
                'desc' => __("Japan's largest bookmarking service to save and share Japanese news, blogs and websites.", 'addthis-share'),
            ),
            'hedgehogs' => array(
                'url' => 'http://www.hedgehogs.net',
                'name' => 'Hedgehogs',
                'category' => 'Social Network',
                'desc' => __("Hedgehogs.net is a social application platform for the hedge fund and investment community.", 'addthis-share'),
            ),
            'historious' => array(
                'url' => 'http://historio.us/',
                'name' => 'historious',
                'category' => 'Bookmarking Site',
                'desc' => __("historious saves you time by helping you find webpages you saw before. Bookmark sites with a single click, then find them again by searching for any word in the content of the page!", 'addthis-share'),
            ),
            'hootsuite' => array(
                'url' => 'https://hootsuite.com/',
                'name' => 'Hootsuite',
                'category' => 'Tools',
                'desc' => __("HootSuite SocialShare helps individuals share and schedule content from wherever they are to multiple social networks simultaneously.", 'addthis-share'),
            ),
            'houzz' => array(
                'url' => 'http://www.houzz.com/',
                'name' => 'Houzz',
                'category' => 'Social Network',
                'desc' => __("Houzz is a platform for home remodeling and design, bringing homeowners and home professionals together in a uniquely visual community.", 'addthis-share'),
            ),
            'w3validator' => array(
                'url' => 'http://validator.w3.org/',
                'name' => 'HTML Validator',
                'category' => 'Tools',
                'desc' => __("The Markup Validator is a free service by W3C that helps check the validity of Web documents.", 'addthis-share'),
            ),
            'indexor' => array(
                'url' => 'http://www.indexor.co.uk/home.php',
                'name' => 'Indexor',
                'category' => 'Bookmarking Site',
                'desc' => __("Its time time to change the way you browse! Indexor provides a personalized homepage service that lets users quickly and easily bookmark there favourite websites.", 'addthis-share'),
            ),
            'instapaper' => array(
                'url' => 'http://www.instapaper.com/',
                'name' => 'Instapaper',
                'category' => 'Tools',
                'desc' => __("Save pages for reading later, then read them when you have time with your web browser, iPhone, or e-reader.", 'addthis-share'),
            ),
            'iorbix' => array(
                'url' => 'http://iorbix.com/',
                'name' => 'iOrbix',
                'category' => 'Social Network',
                'desc' => __("iOrbix is a Social Network where you find friends, share videos, make your business, discuss on forums, plan parties and play games.", 'addthis-share'),
            ),
            'jappy' => array(
                'url' => 'http://www.jappy.de',
                'name' => 'Jappy Ticker',
                'category' => 'Social Network',
                'desc' => __("Jappy.de is a german social network", 'addthis-share'),
            ),
            'kaixin' => array(
                'url' => 'http://www.kaixin001.com/',
                'name' => 'Kaixin Repaste',
                'category' => 'Social Network',
                'desc' => __("Kaixin Repaste is the biggest social network service in China.", 'addthis-share'),
            ),
            'kakao' => array(
                'url' => 'http://www.kakao.com/talk',
                'name' => 'Kakao',
                'category' => 'Social Network',
                'desc' => __("Kakao Talk is a multi-platform texting app that allows iPhone, Android, and BlackBerry users to send and receive messages for free.", 'addthis-share'),
            ),
            'kakaotalk' => array(
                'url' => 'http://www.kakao.com/talk',
                'name' => 'Kakao Talk',
                'category' => 'Other',
                'desc' => __("Kakao Talk is a multi-platform texting app that allows iPhone, Android, and BlackBerry users to send and receive messages for free.", 'addthis-share'),
            ),
            'ketnooi' => array(
                'url' => 'https://play.google.com/store/apps/details?id=com.wketnooi&amp;hl=en',
                'name' => 'Ketnooi',
                'category' => 'Social Network',
                'desc' => __("Ketnooi is one of the most popular Vietnam social networks, and best multi-function forums in Vietnam. You can share, play games, download videos and more.", 'addthis-share'),
            ),
            'kindleit' => array(
                'url' => 'http://fivefilters.org/kindle-it/',
                'name' => 'Kindle It',
                'category' => 'Tools',
                'desc' => __("Kindle It lets you send articles you find on the web to your Kindle or other e-reader for easy reading.", 'addthis-share'),
            ),
            'kledy' => array(
                'url' => 'http://www.kledy.de/',
                'name' => 'Kledy',
                'category' => 'Bookmarking Site',
                'desc' => __("Kledy.de is a social news and bookmark service. Users can share your favorite web sites for free. Kledy.de also provides a bookmark script generator, buttons to link with your own website, microblogging, webcam chat, shopping (with price comparison) and much more.", 'addthis-share'),
            ),
            'lidar' => array(
                'url' => 'https://www.lidar-online.com',
                'name' => 'LiDAR Online',
                'category' => 'Social Network',
                'desc' => __("LiDAR-Online.com is a web platform to market LiDAR, GIS data under login control and security systems. It is based in Dielmo Server Technology to provide services for displaying, using and downloading Geospatial data (Point clouds, Raster, Files) on the Internet in an intuitive user interface.", 'addthis-share'),
            ),
            'lineme' => array(
                'url' => 'http://line.me/',
                'name' => 'LINE',
                'category' => 'Social Network',
                'desc' => __("LINE is a communication app which allows you to make free voice calls and send free messages whenever and wherever you are, 24 hours a day!", 'addthis-share'),
            ),
            'linkedin' => array(
                'url' => 'http://linkedin.com/',
                'name' => 'LinkedIn',
                'category' => 'Social Network',
                'desc' => __("LinkedIn is a business-oriented social networking site that connects experienced professionals around the world, representing 170 industries and 200 countries.", 'addthis-share'),
            ),
            'linkuj' => array(
                'url' => 'http://linkuj.cz/',
                'name' => 'Linkuj.cz',
                'category' => 'Social News',
                'desc' => __("Linkuj.cz is a Czech social sharing community.", 'addthis-share'),
            ),
            'livejournal' => array(
                'url' => 'http://www.livejournal.com/',
                'name' => 'LiveJournal',
                'category' => 'Blogging Platform',
                'desc' => __("LiveJournal is a community publishing platform, willfully blurring the lines between blogging and social networking. LiveJournal has been home to a wide array of creative individuals looking to share common interests, meet new friends, and express themselves.", 'addthis-share'),
            ),
            'mymailru' => array(
                'url' => 'http://my.mail.ru',
                'name' => 'Mail.ru',
                'category' => 'Social Network',
                'desc' => __("Mail.Ru is a Russian Internet company. It was started in 1998 as an e-mail service and went on to become a major corporate figure in the Russian-speaking segment of the Internet, comprising e-mail, instant messenger and online games.", 'addthis-share'),
            ),
            'margarin' => array(
                'url' => 'http://mar.gar.in',
                'name' => 'mar.gar.in',
                'category' => 'Bookmarking Site',
                'desc' => __("Margarine is a social bookmarking site. Use it to save bookmarks, browse other's bookmarks, and make friends.", 'addthis-share'),
            ),
            'markme' => array(
                'url' => 'http://markme.me/',
                'name' => 'Markme',
                'category' => 'Bookmarking Site',
                'desc' => __("Markme is a site that allows you to easily create bookmarks that are stored online to your profile. Your friends or colleagues are able to easily follow your links, while interacting with them in many ways.", 'addthis-share'),
            ),
            'meinvz' => array(
                'url' => 'http://www.meinvz.net/',
                'name' => 'meinVZ',
                'category' => 'Social Network',
                'desc' => __("MeinVZ is a social networking platform for students (in particular for college and university students in Europe) and is based in Berlin, Germany. The name is an abbreviation of the German expression Studentenverzeichnis, which means students' directory.", 'addthis-share'),
            ),
            'memonic' => array(
                'url' => 'http://www.memonic.com',
                'name' => 'Memonic',
                'category' => 'Other',
                'desc' => __("Memonic is a free, web based note-taking software. Keep more than just Bookmarks! Clip any web content and make good use of it. Memonic is your living, breathing notebook.", 'addthis-share'),
            ),
            'mendeley' => array(
                'url' => 'http://www.mendeley.com/',
                'name' => 'Mendeley',
                'category' => 'Other',
                'desc' => __("Mendeley is a free reference manager and academic social network that can help you organize your research, collaborate with others online, and discover the latest research.", 'addthis-share'),
            ),
            'meneame' => array(
                'url' => 'http://www.meneame.net/',
                'name' => 'Meneame',
                'category' => 'Bookmarking Site',
                'desc' => __("Menéame is a social bookmarking destination where subscribers send stories and other users can vote. Voted content is promoted to the homepage.", 'addthis-share'),
            ),
            'messenger' => array(
                'url' => 'https://www.messenger.com/',
                'name' => 'Messenger',
                'category' => 'Social Network',
                'desc' => __("Instantly reach the people in your life, for free. Messenger is just like texting, but you don't have to pay for every message (it works with your data plan).", 'addthis-share'),
            ),
            'stumbleupon' => array(
                'url' => 'http://www.stumbleupon.com',
                'name' => 'MIX',
                'category' => 'Bookmarking Site',
                'desc' => __("StumbleUpon discovers web sites based on your interests, learns what you like and brings you more.", 'addthis-share'),
            ),
            'mixi' => array(
                'url' => 'http://mixi.jp',
                'name' => 'Mixi',
                'category' => 'Social Network',
                'desc' => __("Mixi is a Social Networking Service that allows friends to connect in a fun, convenient way. Mixi users now exceed 27.1 million and has expanded into a communication infrastructure.", 'addthis-share'),
            ),
            'moemesto' => array(
                'url' => 'http://moemesto.ru/',
                'name' => 'Moemesto.ru',
                'category' => 'Bookmarking Site',
                'desc' => __("Moemesto.ru is a popular bookmarking service in Russia.", 'addthis-share'),
            ),
            'mrcnetworkit' => array(
                'url' => 'http://www.mrcnetwork.it',
                'name' => 'mRcNEtwORK',
                'category' => 'Social News',
                'desc' => __("MRCNetwork selects the most interesting news through a collaborative social publishing application: users themselves submit their own favorite news and use a voting system.", 'addthis-share'),
            ),
            'myspace' => array(
                'url' => 'http://www.myspace.com',
                'name' => 'Myspace',
                'category' => 'Social Network',
                'desc' => __("Myspace is a social networking website with an interactive, user-submitted network of friends, personal profiles, blogs, groups, photos, music, and videos for teenagers and adults internationally.", 'addthis-share'),
            ),
            'myvidster' => array(
                'url' => 'http://www.myvidster.com/',
                'name' => 'myVidster',
                'category' => 'Bookmarking Site',
                'desc' => __("myVidster is a social video sharing and bookmarking site that lets you collect and share your favorite videos you find on the web. You can also explore and follow video collections from other users using myVidster.", 'addthis-share'),
            ),
            'n4g' => array(
                'url' => 'http://www.n4g.com',
                'name' => 'N4G',
                'category' => 'Other',
                'desc' => __("N4G is a social game news site that covers the game industry 24 hours a day, 7 days a week.", 'addthis-share'),
            ),
            'naszaklasa' => array(
                'url' => 'http://www.nasza-klasa.pl/',
                'name' => 'Nasza-klasa',
                'category' => 'Social Network',
                'desc' => __("Nasza-klasa.pl, is a large Polish school-based social networking service used by alumni and students.", 'addthis-share'),
            ),
            'netvibes' => array(
                'url' => 'http://www.netvibes.com',
                'name' => 'Netvibes',
                'category' => 'Social News',
                'desc' => __("Netvibes allows you to see everything that’s happening: News, social media, favorite websites, apps and smart devices all in one dashboard.", 'addthis-share'),
            ),
            'netvouz' => array(
                'url' => 'http://www.netvouz.com',
                'name' => 'Netvouz',
                'category' => 'Bookmarking Site',
                'desc' => __("Netvouz is a social bookmark manager where you can store your favorite links online and access them from any computer.", 'addthis-share'),
            ),
            'newsvine' => array(
                'url' => 'http://www.newsvine.com/',
                'name' => 'Newsvine',
                'category' => 'Social News',
                'desc' => __("Newsvine is a community-powered, collaborative journalism news website which draws content from its users and syndicated content from mainstream sources such as The Associated Press. Users can write articles, seed links to external content, and discuss news items submitted by both users and professional journalists.", 'addthis-share'),
            ),
            'nujij' => array(
                'url' => 'http://www.nujij.nl/',
                'name' => 'Nujij',
                'category' => 'Social News',
                'desc' => __("On NUjij, readers are the editors. Anyone can link to interesting, fun and exciting items, and respond to the news of the day. ", 'addthis-share'),
            ),
            'nurses_lounge' => array(
                'url' => 'http://www.nurseslounge.com',
                'name' => 'Nurses Lounge',
                'category' => 'Social Network',
                'desc' => __("Nurses Lounge is a professional network for nurses. Nurses can choose to stay connected and informed to the people, organizations, and information important to their careers.", 'addthis-share'),
            ),
            'odnoklassniki_ru' => array(
                'url' => 'http://www.odnoklassniki.ru',
                'name' => 'Odnoklassniki',
                'category' => 'Social Network',
                'desc' => __("OK.ru is a Russian social network service for classmates and old friends.", 'addthis-share'),
            ),
            'oknotizie' => array(
                'url' => 'http://oknotizie.virgilio.it/',
                'name' => 'OKNOtizie',
                'category' => 'Social News',
                'desc' => __("Oknotizie is an italian social publishing system where users can suggest news items or other resources they find interesting around the net.", 'addthis-share'),
            ),
            'onenote' => array(
                'url' => 'http://www.onenote.com/',
                'name' => 'OneNote',
                'category' => 'Tools',
                'desc' => __("Quickly capture any webpage to OneNote, where you can easily edit, annotate, or share it.", 'addthis-share'),
            ),
            'openthedoor' => array(
                'url' => 'http://www.otd.to',
                'name' => 'OpenTheDoor',
                'category' => 'Bookmarking Site',
                'desc' => __("OpenTheDoor is a place for people to discover and share content from anywhere on the web.", 'addthis-share'),
            ),
            'hotmail' => array(
                'url' => 'https://mail.live.com',
                'name' => 'Outlook',
                'category' => 'Email/IM Service',
                'desc' => __("Email by Microsoft, with address book. Windows Live Hotmail is a best in class e-mail service that helps you organize and manage all your email.", 'addthis-share'),
            ),
            'oyyla' => array(
                'url' => 'http://www.oyyla.com',
                'name' => 'Oyyla',
                'category' => 'Social News',
                'desc' => __("Oyyla is a turkish social news website made for people to discover and share content from anywhere on the Internet, by submitting links and stories, and voting and commenting on submitted links and stories.", 'addthis-share'),
            ),
            'pafnetde' => array(
                'url' => 'http://www.pafnet.de',
                'name' => 'pafnet.de',
                'category' => 'Social Network',
                'desc' => __("Pafnet.de is a leading German social network with 200,000 registered members discussing regional and local events.", 'addthis-share'),
            ),
            'patreon' => array(
                'url' => 'https://www.patreon.com/',
                'name' => 'Patreon',
                'category' => 'Other',
                'desc' => __("Harness the power of your biggest fans by letting them fund your ongoing content creation with a monthly subscription amount of their choice.", 'addthis-share'),
            ),
            'paypalme' => array(
                'url' => 'https://paypal.me/',
                'name' => 'Paypal.Me',
                'category' => 'Other',
                'desc' => __("Create your link, share it, and start receiving money. Split a bill with friends or accept payments from customers. Anyone can use it.", 'addthis-share'),
            ),
            'pdfmyurl' => array(
                'url' => 'http://pdfmyurl.com',
                'name' => 'PDFmyURL',
                'category' => 'Tools',
                'desc' => __("PDFmyURL is a new free tool that lets you convert any url / webpage to a .pdf and download it instantly. PDF's look excactly like the webpage, it renders all css and javascript", 'addthis-share'),
            ),
            'pinboard' => array(
                'url' => 'https://pinboard.in/',
                'name' => 'Pinboard',
                'category' => 'Bookmarking Site',
                'desc' => __("Pinboard is a fast, no-nonsense bookmarking site for people who value privacy and speed.", 'addthis-share'),
            ),
            'pinterest_share' => array(
                'url' => 'http://www.pinterest.com',
                'name' => 'Pinterest',
                'category' => 'Social Network',
                'desc' => __("Pinterest lets you organize and share all the beautiful things you find on the web. People use pinboards to plan their weddings, decorate their homes, and organize their favorite recipes. Best of all, you can browse pinboards created by other people. Browsing pinboards is a fun way to discover new things and get inspiration from people who share your interests.", 'addthis-share'),
            ),
            'plurk' => array(
                'url' => 'http://www.plurk.com',
                'name' => 'Plurk',
                'category' => 'Social Network',
                'desc' => __("Plurk is a social journal for your life. Share your life easily with friends, family and fans.", 'addthis-share'),
            ),
            'pocket' => array(
                'url' => 'http://getpocket.com',
                'name' => 'Pocket',
                'category' => 'Tools',
                'desc' => __("When you find something you want to view later, put it in Pocket. Save directly from your browser or from apps like Twitter, Flipboard, Pulse and Zite.", 'addthis-share'),
            ),
            'posteezy' => array(
                'url' => 'http://www.posteezy.com',
                'name' => 'Posteezy',
                'category' => 'Blogging Platform',
                'desc' => __("Posteezy is a microblogging and link sharing startup that lets you post anything with no login.", 'addthis-share'),
            ),
            'print' => array(
                'url' => '',
                'name' => 'Print',
                'category' => 'Tools',
                'desc' => __("Addthis menu print service.", 'addthis-share'),
            ),
            'printfriendly' => array(
                'url' => 'http://www.printfriendly.com',
                'name' => 'PrintFriendly',
                'category' => 'Tools',
                'desc' => __("PrintFriendly makes printing on the web better. You'll save paper and ink, plus get great looking documents.", 'addthis-share'),
            ),
            'pusha' => array(
                'url' => 'http://www.pusha.se',
                'name' => 'Pusha',
                'category' => 'Bookmarking Site',
                'desc' => __("Pusha is a place where the members themselves decide the content by sharing, voting on, and discussing fun and interesting links.", 'addthis-share'),
            ),
            'qrsrc' => array(
                'url' => 'http://www.qrsrc.com',
                'name' => 'QRSrc.com',
                'category' => 'Tools',
                'desc' => __("QRSrc allows you to create and share QR Codes for text, url, sms, phone numbers.", 'addthis-share'),
            ),
            'quantcast' => array(
                'url' => 'http://quantcast.com',
                'name' => 'Quantcast',
                'category' => 'Tools',
                'desc' => __("Quantcast provides audience and demographic data for over 100 million web and mobile destinations that have opted to participate in Quantcast Measure.", 'addthis-share'),
            ),
            'qzone' => array(
                'url' => 'http://qzone.qq.com/',
                'name' => 'Qzone',
                'category' => 'Social Network',
                'desc' => __("Qzone is the largest social networking site in China with 500 million users.", 'addthis-share'),
            ),
            'reddit' => array(
                'url' => 'http://www.reddit.com/',
                'name' => 'Reddit',
                'category' => 'Social News',
                'desc' => __("Reddit is a social news website on which users can post links to content on the Internet. Other users may then vote the posted links up or down, causing them to become more or less prominent on the home page.", 'addthis-share'),
            ),
            'rediff' => array(
                'url' => 'http://mypage.rediff.com',
                'name' => 'Rediff MyPage',
                'category' => 'Social Network',
                'desc' => __("Rediff MyPage helps you connect with people who matter and stay updated by sharing instant info, photos, and more.", 'addthis-share'),
            ),
            'renren' => array(
                'url' => 'http://www.renren.com/',
                'name' => 'Renren',
                'category' => 'Social Network',
                'desc' => __("The Renren Network is a Chinese social networking service popular among college students.", 'addthis-share'),
            ),
            'researchgate' => array(
                'url' => 'http://www.researchgate.net/',
                'name' => 'ResearchGate',
                'category' => 'Social Network',
                'desc' => __("ResearchGate allows you to network with the largest global community dedicated to science and research: we help you to expand your contacts, share knowledge and find potential research partners.", 'addthis-share'),
            ),
            'safelinking' => array(
                'url' => 'http://safelinking.net/',
                'name' => 'Safelinking',
                'category' => 'Tools',
                'desc' => __("Safelinking.net is an online service, free of charge, that provides Internet users with a facility that helps them hiding their links (URL) when they are being shared online, particularly on social networks.", 'addthis-share'),
            ),
            'scoopit' => array(
                'url' => 'http://www.scoop.it',
                'name' => 'Scoop.it',
                'category' => 'Social News',
                'desc' => __("Scoop.it is a content marketing software company. The company operates the Scoop.it platform, a content curation service, and markets its software to businesses.", 'addthis-share'),
            ),
            'sinaweibo' => array(
                'url' => 'http://t.sina.com.cn/',
                'name' => 'Sina Weibo',
                'category' => 'Social Network',
                'desc' => __("Sina Weibo is a Chinese microblogging website. Akin to a hybrid of sites Facebook and Twitter, it is one of the most popular sites in China, in use by well over 30% of Internet users, with a market penetration similar to the United States' Twitter.", 'addthis-share'),
            ),
            'skype' => array(
                'url' => 'https://skype.com/',
                'name' => 'Skype',
                'category' => 'Other',
                'desc' => __("Skype keeps the world talking. Video call, message and share with anyone for free, even if they're not on Skype.", 'addthis-share'),
            ),
            'skyrock' => array(
                'url' => 'http://www.skyrock.com/',
                'name' => 'Skyrock Blog',
                'category' => 'Blogging Platform',
                'desc' => __("Skyrock.com is a social networking site based in France that offers a free space on the web to allow its users to create blogs, add profiles, and exchange messages with other registered members.", 'addthis-share'),
            ),
            'slack' => array(
                'url' => 'https://slack.com/',
                'name' => 'Slack',
                'category' => 'Other',
                'desc' => __("Slack brings all your communication together in one place. It's real-time messaging, archiving and search for modern teams.", 'addthis-share'),
            ),
            'sms' => array(
                'url' => '',
                'name' => 'SMS',
                'category' => 'Other',
                'desc' => __("Share in a text message.", 'addthis-share'),
            ),
            'sodahead' => array(
                'url' => 'http://www.sodahead.com/',
                'name' => 'SodaHead',
                'category' => 'Other',
                'desc' => __("SodaHead is a self-described 'opinion site' that allows creation of polls and questions which can be used to gather the opinions of other users.", 'addthis-share'),
            ),
            'spinsnap' => array(
                'url' => 'http://www.spinsnap.com',
                'name' => 'SpinSnap',
                'category' => 'Bookmarking Site',
                'desc' => __("SpinSnap.com is a Discovery Engine.  SpinSnap allows you to discover and share new and exciting websites, music, videos and daily deals.  Most people discover websites they would not normally encounter in their everyday internet travels.", 'addthis-share'),
            ),
            'startaid' => array(
                'url' => 'http://www.startaid.com',
                'name' => 'Startaid',
                'category' => 'Bookmarking Site',
                'desc' => __("StartAid is perfect for saving all your Bookmarks and Favorites Online. You can quickly access your Bookmarks and Favorites from any computer and best of all, you will never lose a site again.", 'addthis-share'),
            ),
            'startlap' => array(
                'url' => 'http://www.startlap.hu/',
                'name' => 'Startlap',
                'category' => 'Bookmarking Site',
                'desc' => __("Startlap is a bookmarking service allowing users to tag, save, and manage their saved links. It also provides interesting websites (categorized by favorite tags, searchable by keywords) and a daily updated list of favorite sites based on the most saved links.", 'addthis-share'),
            ),
            'studivz' => array(
                'url' => 'http://www.studivz.net',
                'name' => 'studiVZ',
                'category' => 'Social Network',
                'desc' => __("studiVZ.net is a german social network that enables students to exchange information.", 'addthis-share'),
            ),
            'stuffpit' => array(
                'url' => 'http://www.stuffpit.com/',
                'name' => 'Stuffpit',
                'category' => 'Shopping Site',
                'desc' => __("Share the latest products, deals and offers you find online with your followers and earn money everytime they make a purchase.", 'addthis-share'),
            ),
            'stumpedia' => array(
                'url' => 'http://www.stumpedia.com',
                'name' => 'Stumpedia',
                'category' => 'Other',
                'desc' => __("Stumpedia.com is a social search engine that relies on human participation to index, organize, and review the world wide web.", 'addthis-share'),
            ),
            'surfingbird' => array(
                'url' => 'http://surfingbird.ru',
                'name' => 'Surfingbird',
                'category' => 'Bookmarking Site',
                'desc' => __("Surfingbird is a web-page recommendation system that makes internet surfing easy and convenient.", 'addthis-share'),
            ),
            'svejo' => array(
                'url' => 'http://svejo.net/',
                'name' => 'Svejo',
                'category' => 'Social News',
                'desc' => __("Bulgarian social news website made for people to discover and share content from anywhere on the Internet, by submitting links and stories, and voting and commenting on submitted links and stories.", 'addthis-share'),
            ),
            'symbaloo' => array(
                'url' => 'http://symbaloo.com',
                'name' => 'Symbaloo',
                'category' => 'Other',
                'desc' => __("Symbaloo is a visual bookmarking tool that makes it simple and fun to organize the best of the web. You have all your favorite websites at your fingertips. With an account you can access your bookmarks from everywhere with any device and share your online resources with others.", 'addthis-share'),
            ),
            'taringa' => array(
                'url' => 'http://www.taringa.net/',
                'name' => 'Taringa!',
                'category' => 'Social Network',
                'desc' => __("Taringa! is an information sharing community where the users create the content together and vote on what they like the most.", 'addthis-share'),
            ),
            'telegram' => array(
                'url' => 'http://www.telegram.org',
                'name' => 'Telegram',
                'category' => 'Social Network',
                'desc' => __("Telegram is a cloud-based mobile and desktop messaging app with a focus on security and speed.", 'addthis-share'),
            ),
            'tencentqq' => array(
                'url' => 'http://im.qq.com/',
                'name' => 'Tencent QQ',
                'category' => 'Social Network',
                'desc' => __("Tencent QQ is a Chinese instant messaging service. QQ also offers services that provide online social games, music, shopping, microblogging, movies, and group and voice chat.", 'addthis-share'),
            ),
            'tencentweibo' => array(
                'url' => 'http://t.qq.com/',
                'name' => 'Tencent Weibo',
                'category' => 'Social Network',
                'desc' => __("Tencent Weibo is a Chinese microblogging website launched by Tencent.", 'addthis-share'),
            ),
            'trello' => array(
                'url' => 'https://trello.com/',
                'name' => 'Trello',
                'category' => 'Other',
                'desc' => __("Trello lets you work more collaboratively and get more done. Trello’s boards, lists, and cards enable you to organize and prioritize your projects in a fun, flexible and rewarding way.", 'addthis-share'),
            ),
            'tuenti' => array(
                'url' => 'http://www.tuenti.com/',
                'name' => 'Tuenti',
                'category' => 'Social Network',
                'desc' => __("Tuenti is a social networking platform that is designed to improve communication and information sharing between people who know each other. It is a private platform so you can only register if you've received an invitation from another user.", 'addthis-share'),
            ),
            'tumblr' => array(
                'url' => 'http://www.tumblr.com/',
                'name' => 'Tumblr',
                'category' => 'Blogging Platform',
                'desc' => __("Tumblr lets you effortlessly share anything. Post text, photos, quotes, links, music, and videos, from your browser, phone, desktop, email, or wherever you happen to be. You can customize everything, from colors, to your theme's HTML. ", 'addthis-share'),
            ),
            'twitter' => array(
                'url' => 'http://twitter.com/',
                'name' => 'Twitter',
                'category' => 'Blogging Platform',
                'desc' => __("Twitter is a free social networking and micro-blogging service that enables its users to send and read messages known as tweets. Tweets are text-based posts of up to 140 characters displayed on the author's profile page and delivered to the author's subscribers who are known as followers. ", 'addthis-share'),
            ),
            'typepad' => array(
                'url' => 'http://www.typepad.com/',
                'name' => 'Typepad',
                'category' => 'Blogging Platform',
                'desc' => __("TypePad is the premier blogging service for professionals and small businesses. TypePad hosts many popular blogs and small business websites.", 'addthis-share'),
            ),
            'urlaubswerkde' => array(
                'url' => 'http://www.urlaubswerk.de',
                'name' => 'Urlaubswerk',
                'category' => 'Social Network',
                'desc' => __("Urlaubswerk is a German travel site, similar to TripAdvisor.", 'addthis-share'),
            ),
            'venmo' => array(
                'url' => 'https://venmo.com/',
                'name' => 'Venmo',
                'category' => 'Other',
                'desc' => __("Venmo is a mobile payment service. It allows users to transfer money between one another using a mobile phone app or web interface. Venmo currently has around 203 million active users.", 'addthis-share'),
            ),
            'viadeo' => array(
                'url' => 'http://www.viadeo.com/fr/connexion/',
                'name' => 'Viadeo',
                'category' => 'Social Network',
                'desc' => __("Viadeo is a business and social networking tool to develop your business and career.", 'addthis-share'),
            ),
            'viber' => array(
                'url' => 'http://www.viber.com/',
                'name' => 'Viber',
                'category' => 'Other',
                'desc' => __("Viber is a mobile application that allows you to make phone calls and send text messages to all other Viber users for free.", 'addthis-share'),
            ),
            'virb' => array(
                'url' => 'http://www.virb.com',
                'name' => 'Virb',
                'category' => 'Other',
                'desc' => __("Virb lets you build your own website quickly and easily. ", 'addthis-share'),
            ),
            'visitezmonsite' => array(
                'url' => 'http://www.visitezmonsite.com',
                'name' => 'Visitez Mon Site',
                'category' => 'Bookmarking Site',
                'desc' => __("VisitezMonSite is a French bookmarking site, similar to Digg, that allows users to vote on content submitted by other users.", 'addthis-share'),
            ),
            'vk' => array(
                'url' => 'http://vk.com/',
                'name' => 'Vkontakte',
                'category' => 'Social Network',
                'desc' => __("VKontakte.ru is the most popular social network service in Russia, Ukraine, Belarus and Kazakhstan.", 'addthis-share'),
            ),
            'vkrugudruzei' => array(
                'url' => 'http://vkrugudruzei.ru',
                'name' => 'vKruguDruzei',
                'category' => 'Social Network',
                'desc' => __("vKrurguDruzei.ru is one of the oldest Russian-language social network services for classmates and friends, popular in Russia, Ukraine, Belarus, Kazakhstan and other countries. The website allows you to keep in touch with friends, get to know new friends, learn more about the people that you meet, upload an unlimited number of photos, and exchange audio and video content.", 'addthis-share'),
            ),
            'vybralisme' => array(
                'url' => 'http://vybrali.sme.sk/',
                'name' => 'vybrali SME',
                'category' => 'Bookmarking Site',
                'desc' => __("The most popular bookmarking service in Slovakia and Czech republic.", 'addthis-share'),
            ),
            'wanelo' => array(
                'url' => 'http://wanelo.com',
                'name' => 'Wanelo',
                'category' => 'Social Network',
                'desc' => __("Wanelo is a community for all of the world's shopping. It brings together all stores and products into a single social platform, unfettered by advertising. You can buy almost everything you see on Wanelo, and everything is posted by users.", 'addthis-share'),
            ),
            'internetarchive' => array(
                'url' => 'https://archive.org/index.php',
                'name' => 'Wayback Machine',
                'category' => 'Other',
                'desc' => __("Internet Archive is a non-profit digital library offering free universal access to books, movies, music, as well as 439 billion archived web pages.", 'addthis-share'),
            ),
            'weheartit' => array(
                'url' => 'http://www.weheartit.com/',
                'name' => 'We Heart It',
                'category' => 'Social Network',
                'desc' => __("We Heart It is your home for inspiring images and the people who heart them.", 'addthis-share'),
            ),
            'sharer' => array(
                'url' => 'http://events.webmoney.ru',
                'name' => 'WebMoney',
                'category' => 'Social Network',
                'desc' => __("Social network for WebMoney Transfer's users.", 'addthis-share'),
            ),
            'wechat' => array(
                'url' => 'http://www.wechat.com/',
                'name' => 'WeChat',
                'category' => 'Social Network',
                'desc' => __("WeChat is a free messaging &amp; calling app that allows you to easily connect with family &amp; friends across countries.", 'addthis-share'),
            ),
            'whatsapp' => array(
                'url' => 'https://www.whatsapp.com/',
                'name' => 'WhatsApp',
                'category' => 'Other',
                'desc' => __("WhatsApp Messenger is a cross-platform mobile messaging app which allows you to exchange messages without having to pay for SMS.", 'addthis-share'),
            ),
            'domaintoolswhois' => array(
                'url' => 'http://whois.domaintools.com/',
                'name' => 'Whois Lookup',
                'category' => 'Tools',
                'desc' => __("WHOIS is a utility used to look up information on domain names. This includes contact information as well as some technical information such as the domain's name servers (DNS) used for service, and certain status information such as if the domain is locked.", 'addthis-share'),
            ),
            'wishmindr' => array(
                'url' => 'http://wishmindr.com',
                'name' => 'WishMindr',
                'category' => 'Tools',
                'desc' => __("WishMindr is a free wish list maker and reminders service for any occasion. Once a list is created, you can easily add contacts from Yahoo! or Gmail accounts and set-up automatic reminder emails for your wish list, just in time for the occasion.", 'addthis-share'),
            ),
            'wordpress' => array(
                'url' => 'http://wordpress.com/',
                'name' => 'WordPress',
                'category' => 'Blogging Platform',
                'desc' => __("A semantic personal publishing platform with a focus on aesthetics, web standards, and usability.", 'addthis-share'),
            ),
            'wykop' => array(
                'url' => 'http://www.wykop.pl',
                'name' => 'Wykop',
                'category' => 'Social News',
                'desc' => __("wykop.pl is a Polish social networking service. It is modeled after the American website digg.com (wykop in Polish language means unearth! or dig out!), it's also very similar to reddit.com.", 'addthis-share'),
            ),
            'xing' => array(
                'url' => 'https://www.xing.com/',
                'name' => 'XING',
                'category' => 'Social Network',
                'desc' => __("Around the world every day, over 9 million business professionals use XING, the global business network,  in 16 languages to do business and promote their career.", 'addthis-share'),
            ),
            'yahoomail' => array(
                'url' => 'http://mail.yahoo.com/',
                'name' => 'Yahoo Mail',
                'category' => 'Email/IM Service',
                'desc' => __("Email by Yahoo, with address book.", 'addthis-share'),
            ),
            'yammer' => array(
                'url' => 'http://www.yammer.com/',
                'name' => 'Yammer',
                'category' => 'Blogging Platform',
                'desc' => __("Yammer is a tool for making companies and organizations more productive through the exchange of short frequent answers to one simple question: 'What are you working on?'", 'addthis-share'),
            ),
            'yoolink' => array(
                'url' => 'http://www.yoolink.fr/',
                'name' => 'Yoolink',
                'category' => 'Bookmarking Site',
                'desc' => __("YoolinkPro is a customizable communication platform that enables you to create a corporate social network, to easily manage external communities or to boost your team productivity. Share with your external networks’ members (clients, suppliers, etc.) without giving them access.", 'addthis-share'),
            ),
            'yummly' => array(
                'url' => 'http://www.yummly.com',
                'name' => 'Yummly',
                'category' => 'Bookmarking Site',
                'desc' => __("Yummly is a mobile app and website that provides recipe recommendations personalized to the individual's tastes, semantic recipe search, a digital recipe box, shopping list and one-hour grocery delivery.", 'addthis-share'),
            ),
            'yuuby' => array(
                'url' => 'http://www.yuuby.com',
                'name' => 'Yuuby',
                'category' => 'Social Network',
                'desc' => __("Yuuby is a social network. You can meet friends, share photos, links, comments and more.", 'addthis-share'),
            ),
            'zakladoknet' => array(
                'url' => 'http://www.zakladok.net/',
                'name' => 'Zakladok.net',
                'category' => 'Bookmarking Site',
                'desc' => __("Zakladok.net lets you save public and personal bookmarks, exchange bookmarks, and comment on bookmarks of other users. Zakladok.net shares the user base of Interesno.com social network, so if you're registered on either of them - you can use both.", 'addthis-share'),
            ),
            'ziczac' => array(
                'url' => 'http://ziczac.it',
                'name' => 'ZicZac',
                'category' => 'Social News',
                'desc' => __("ZicZac is one of the most popular Social News websites in Italy", 'addthis-share'),
            ),
            'zingme' => array(
                'url' => 'http://me.zing.vn',
                'name' => 'ZingMe',
                'category' => 'Social Network',
                'desc' => __("Zing Me is the largest social network in Vietnam. Zing Me is a product of VNG Corporation.", 'addthis-share'),
            ),

        );

        // TODO add some filters...
        $vendors = $addthis_share_vendors;

        if ($return === 'keys') {
            return array_keys($vendors);
        }

        if ($return === 'customizer') {
            $customizer = array();

            foreach ($vendors as $id => $service) :
                $customizer[$id] = esc_html($service['name']);
            endforeach;
            return $customizer;
        }

        return $vendors;
    }
endif;
